# 站点基础
title: "Steven Zhang"
description: "CV / Weakly Supervised Segmentation • Active Learning • LLM"
url: "https://steven-zn.github.io"
baseurl: ""

# 使用 Minimal Mistakes 主题（GitHub Pages 兼容）
remote_theme: "mmistakes/minimal-mistakes"

# 主题皮肤与外观
skin: "aqua"

# 作者信息
locale: en-US
author:
  name: "Nuojunxi (Steven) Zhang"
  avatar: "/images/avatar.jpg"
  bio: "CS @ Kean University • AI Research • Medical Imaging"
  location: "Union, New Jersey, USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:zhangnuojunxi@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Steven-ZN"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/your-link"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=YOURID"

# 导航
collections:
  pages:
    output: true
    permalink: /:categories/:title/

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache  

# SEO
seo:
  type: "Person"
  name: "Steven Zhang"

# 分页（博客）
paginate: 6
paginate_path: "/blog/page:num/"

# 代码高亮
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# 默认 Front Matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      toc: true
      toc_sticky: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Assets
sass:
  sass_dir: _sass
  style: compressed

# 站点图标
# favicon: /images/favicon.ico
